name: Update vault content

on:
  schedule:
    - cron: "0 11 * * MON" # Run every Monday at 11 AM UTC
  workflow_dispatch:

jobs:
  update_vault_content:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Obsidian Vault
        uses: actions/checkout@v4.2.2
        with:
          repository: "rushabhcodes/garden"
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: garden

      - name: Clone this repo
        uses: actions/checkout@v4.2.2
        with:
          ref: v4
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: quartz

      - name: Delete everything in content/ except index.md
        run: |
          cd quartz
          mv content/index.md .
          rm -rf content
          mkdir content
          mv index.md content

      - name: Copy over media and files
        run: |
          cd garden
          echo "----- Copying over public-only attachments"
          cp -vr attachments/. ../quartz/content
          echo -e "\n----- Copying over Markdown files"
          cp -vr notes/. ../quartz/content
          cd ../quartz/content
        #   mv attachments _files
        # ^ Include this last line if you want to rename your public folder

      - name: Print out current state of filesystem
        run: |
          echo "----- Folder: quartz/"
          cd quartz
          ls | cat
          echo -e "\n----- Folder: quartz/content/"
          ls content | cat
          echo -e "\n----- Folder: quartz/content/attachments"
          ls content/attachments | cat
        # ^ NOTE: this uses the renamed folder name from above

      - name: Install Bun just to run literally two commands
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd quartz
          bun i

      - name: Setup Git config (user and email), necessary for commits
        run: |
          git config --global user.name "Rushabh Patil"
          git config --global user.email "rushabhpatil.dev@gmail.com"

      - name: Sync Quartz repo
        run: |
          cd quartz
          bun quartz sync