name: Update vault content

on:
  repository_dispatch:
    types: [vault-updated]
  schedule:
    - cron: "0 11 * * MON" # Run every Monday at 11 AM UTC
  workflow_dispatch:

jobs:
  update_vault_content:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Obsidian Vault
        uses: actions/checkout@v4.2.2
        with:
          repository: "rushabhcodes/garden"
          ref: main
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: garden

      - name: Clone this repo
        uses: actions/checkout@v4.2.2
        with:
          ref: v4
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          path: quartz

      - name: Delete everything in content/
        run: |
          cd quartz
          rm -rf content
          mkdir content

      - name: Copy over media and files
        run: |
          rsync -av --exclude='*/private/' --exclude='.*' garden/ quartz/content/

      - name: Print out current state of filesystem
        run: |
          echo "----- Folder: quartz/"
          cd quartz
          ls | cat
          echo -e "\n----- Folder: quartz/content/"
          ls content | cat

      - name: Install Bun just to run literally two commands
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          cd quartz
          bun i

      - name: Setup Git config (user and email), necessary for commits
        run: |
          git config --global user.name "Rushabh Patil"
          git config --global user.email "rushabhpatil.dev@gmail.com"

      - name: Sync Quartz repo
        run: |
          cd quartz
          bun quartz sync